### ISSUE TITLE
Consider building the docker image with azd

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/openai-aca-lb#11]
Currently the bicep hard-codes an image at "andrewdewes". This seems non-ideal since:

1) Developers may be uncomfortable with a personally associated image
2) If a developer tweaks the code, it's not easy to run azd up again to update the image

Instead, azd could do the packaging and storage of the image. The main drawback is that docker is required for the packaging step. Thoughts?

**Comment by pamelafox** [comment]
Did you have thoughts on this @andredewes ?

**Comment by andredewes** [comment]
Using `az acr build ` to build the container now.
