### ISSUE TITLE
Support for response streaming

### ISSUE THREAD

**Issue by denniszielke** [Azure-Samples/openai-aca-lb#12]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
I want response streaming which is using ServerSide Events to ensure that long running LLM prompts return quickly.
https://cookbook.openai.com/examples/how_to_stream_completions

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by andredewes** [comment]
This solution does support streaming!
