### ISSUE TITLE
azd-hooks/postprovision.sh: Permission denied when trying to azd up

### ISSUE THREAD

**Issue by adp-douglaswross** [Azure-Samples/openai-aca-lb#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 
1. clone the repo
2. azd up
3. Most of the infra is created, then running azd-hooks/postprovision.sh - permission denied in the script

### Any log messages given by the failure
>
/bin/sh: azd-hooks/postprovision.sh: Permission denied

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '126', Path: 'azd-hooks/postprovision.sh'. : exit code: 126

ERROR: error executing step command 'provision': failed running post hooks: 'postprovision' hook failed with exit code: '126', Path: 'azd-hooks/postprovision.sh'. : exit code: 126
### Expected/desired behavior
>

### OS and Version?
> 
macOS Sonoma 14.4.1
Found this from azure-search-openai-demo - that installs perfectly, so not sure if I am not setting some permissions appropriately, although I have myself at full access in my subscription, so I am guessing it is not something I have not setup

### Versions
>

### Mention any other details that might be useful

Also checking if this is being actively worked on

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diberry** [comment]
The readme needs to say you need to login with az before doing the azd up: 

1. az login --use-device-code
2. azd auth login --use-device-code
3. azd up

**Comment by andredewes** [comment]
Fixed the permission issue and updated the README instructions.
